"""
Signals.

Functions and constants for dealing with BPA signals.

Some properties of the signals...
>>> len(SIGNALS)
1253
>>> len([s for s in SIGNALS if s.endswith('Mag')])
602
>>> len([s for s in SIGNALS if s.endswith('Ang')])
602
>>> len([s for s in SIGNALS if s.endswith('Frequency')])
49
>>> 602 + 602 + 49
1253
>>> len([s for s in SIGNALS if "Voltage" in s])
760
>>> len([s for s in SIGNALS if "Current" in s])
444
>>> 760 + 444 + 49
1253
>>> len([s for s in SIGNALS if s.endswith('Voltage Mag')])
380

Voltage Signals all have three phases, except for a few
(possibly mislabeled) odd ones...
>>> (map,mp) = cluster_phase_signals([s for s in SIGNALS if "Volt" in s])
>>> oddones = [g for g in map if len(map[g]) != 3]

>>> len(oddones)
4
>>> len([o for o in oddones if o.startswith("Dooley data PMU #2")])
2
>>> len([o for o in oddones if o.startswith("John Day 230 A1 SA - Xfmr")])
2

Some common usages...
>>> bo = by_origin_site(SIGNALS)
>>> (sigmap,multiphase) = cluster_phase_signals(bo['Imrie'])
>>> len(multiphase)
4
>>> len(sigmap)
11
>>> len(sigmap['Imrie data PMU - 230 Main Bus Voltage Mag'])
3

"""
import re   
import logging
import datetime as dt
from matplotlib import pyplot
import faults
import numpy as np

_PHASERE = re.compile(' [ABC] [Pp]hase')

def match_pod_to_signal(pod,saved_quasi_matches=None):
    """Match a line from the fault database's rawpod format
    against known signals.

    arguments:
    pod -- a line formatted in the style of BPA's raw pod
    saved_quasi_matches -- (optional) a list that near matches
      (those with a different line number) will be placed in
      
    Returns the exact matching signal, or raises a KeyError

    The Raw pod for fault (1,0) on 10/17/12:
    >>> pod = 'Grizzly-Summer Lake No 1 500kV line'
    >>> match_pod_to_signal(pod)
    'Grizzly 500 A1 SA - Summer Lake #1 Current Mag'
    >>> match_pod_to_signal(pod) in SIGNALS
    True

    """
    m = faults.FAULT_POD_FORMAT.match(pod)
    (origin, dest, lineno, nominal_v) = m.groups()
    lineno_str = '#'+lineno
    for s in SIGNALS:
        if origin in s and dest in s and nominal_v in s:
            if lineno_str in s:
                return s
            elif saved_quasi_matches != None:
                saved_quasi_matches.append(s)

    raise KeyError("No Exact Match for '%s'"%(pod))
    
def iloc_of_time(df, time):
   """Find the iloc of a specified time.  If we move to indexing
   the dataframe by time, we won't need this anymore!
   """

   df_t0 = df['DateTime'].iloc[0]
   offset = timedelta_to_cycles(time-df_t0)
   assert offset > 0, "iloc would preceed the start of the DataFrame!"
   assert offset < df.shape[0], "DataFrame doesn't have enough rows!"
   df_t = df['DateTime'].iloc[offset]
   assert df_t == time, "Time mismatch! Are the rows contiguous cycles?"

   return offset

def timedelta_to_cycles(td):
    """Convert a datetime.timedelta to a number of cycles (60/sec)

    >>> timedelta_to_cycles(dt.timedelta(seconds=1))
    60
    >>> timedelta_to_cycles(dt.timedelta(seconds=-1))
    -60
    """
    
    # add one to the microseconds to force a round up prior
    # to casting as int...
    # 5184000 = cycles in a day
    return td.days*5184000+td.seconds*60+(((td.microseconds+1)*60)/1000000)

def phases(signals):
    """Take a list of 3 signals, and find the A,B & C phases

    Returns a dictionary with keys 'A', 'B' & 'C'

    >>> (map,mps) = cluster_phase_signals(SIGNALS)
    >>> p = phases(map[mps.pop()])
    >>> 'A Phase' in p['A'] or 'A phase' in p['A']
    True
    
    """
    
    assert len(signals) == 3
    p = {}
    for s in signals:
        if 'A phase' in s or 'A Phase' in s:
            p['A'] = s
        elif 'B phase' in s or 'B Phase' in s:
            p['B'] = s
        elif 'C phase' in s or 'C Phase' in s:
            p['C'] = s
        else:
            raise KeyError
    return p


def salient_sites(faultinst):
    """Given a fault instance, return all the sites that
    occur in the faultinstance's rawpod"""

    return [s for s in SITES if s in faultinst.rawpod]

def salient_signals(faultinst, signal_criterion):
    """Given a fault instance, find the salient sites and from
    these sites find a set of signals that pass the signal_criterion.

    signal_criterion - a function that takes a signal as input
          (e.g.,: lambda x: x.endswith('Voltage Mag'))
    """
    sites = salient_sites(faultinst)

    s_signals = []
    for sig in SIGNALS:
        if signal_criterion(sig):
            for site in sites:
                if site in sig:
                    s_signals.append(sig)
                    break
    return s_signals


def by_origin_site(signals):
    """cluster signals by origin site:
    return a dictionary mapping:
    site -> [signals beginning with site]
    """
    c = {s:[] for s in SITES}
    for s in signals:
        for site in SITES:
            if s.startswith(site):
                c[site].append(s)
                break
        else:
            raise KeyError("Site not found for signal %s"%(s))
    return c

def by_connected_site(signals):
    """cluster signals by site name (regardless of where it appears
    in the signal name. Returns a dictionary mapping:
    site -> [signals containing site]"""
    c = {s:[] for s in SITES}
    for s in signals:
        for site in SITES:
            if site in s:
                c[site].append(s)
    return c

def get_origin(signal):
    """Find the origin site of a given signal

    >>> get_origin('Rock Creek 500 A1 SA - West Bus Voltage Mag')
    'Rock Creek'
    """

    possible = [s for s in SITES if signal.startswith(s)]
    assert len(possible) == 1, "Origin is ambiguous or unknown!"
    return possible[0]


def get_generic_signal(signal):
    """Returns a generic version of a phased-signal.
    >>> ps = 'Big Eddy 500 A1 SA - A phase West Bus Voltage Mag'
    >>> ps in SIGNALS
    True
    >>> gs = get_generic_signal(ps)
    >>> gs
    'Big Eddy 500 A1 SA - West Bus Voltage Mag'
    >>> gs in SIGNALS
    True
    
"""
    return _PHASERE.sub('', signal)


def cluster_phase_signals(columns):
    """Cluster signals by forming a signal map such that
    non-phased-signal -> [phased variants]

    return (signal map, [signals with 1 or more variants])

    >>> (m,mps) = cluster_phase_signals(SIGNALS[:8])
    >>> len(m)
    2
    >>> len(mps)
    2
    """

    # first pass: find all "generic" signals (without a phase)
    phased_signals = {}
    for c in columns:
        if not _PHASERE.search(c):
            phased_signals[c] = []
    
    # second pass:  find signals with a "phase"
    # look for things like 'Alvery 500kv A1 - A phase Voltage Mag'
    # match these to a "generic" signal, 
    # warn if there is no generic signal
    multiphased_signals = set([])
    for c in columns:
        if _PHASERE.search(c):
            template = _PHASERE.sub('', c)
            if not (template in phased_signals):
                logging.warning("'%s' -- Can't find generic version (skipping)"%(c))
            else:
                phases = phased_signals[template]
                phases.append(c)
                multiphased_signals.add(template)

    # now:
    # phased_signals maps 'generic signal' -> list of phased signals
    # multiphased_signals is a subset of keys from phased_signals 
    #   (those with non-empty list)
    return (phased_signals, multiphased_signals)


def find_steadystate(df, nrows, column,
                     leftedge_i=None, rightedge_i=None,
                     r_to_l=True, sagthresh=.9, edgethresh=.01):
    """Find a steady state signal for a specified column.
    """
    if leftedge_i == None:
        leftedge_i = 0
    if rightedge_i == None:
        rightedge_i = df.shape[0]

    assert nrows > 0, "nrows must be positive"
    assert leftedge_i >= 0, "left edge out of bounds"
    assert rightedge_i <= df.shape[0], "right edge out of bounds"
    assert leftedge_i + nrows <= rightedge_i, "edges are too narrow!"

    columndata = df[column]
    if r_to_l:
        ei = rightedge_i
        si = rightedge_i - nrows
        incr = -1
        stop = leftedge_i
    else:
        si = leftedge_i
        ei = leftedge_i + nrow
        incr = 1
        stop = rightedge_i - nrows
        
    while si != stop:
        w = columndata.iloc[si:ei]
        w_mean = w.mean()
        w_min = w.min()
        edgemin = (1.0-edgethresh)*w_mean
        assert (columndata.iloc[si] == w.iloc[0] or
                (np.isnan(columndata.iloc[si]) and np.isnan(w.iloc[0])))
        
        if (w_min > sagthresh*w_mean and w.iloc[0] > edgemin and
                w.iloc[-1] > edgemin):
            
            return (si, ei, w_mean)

        si += incr
        ei += incr

    return None
    


SITES = [
    'Allston',
    'Alvey',
    'Bell',
    'Big Eddy',
    'Captain Jack',
    'Central Ferry',
    'Chief Joseph',
    'Custer',
    'Dodge Junction',
    'Dooley',
    'Echo Lake',
    'Garrison',
    'Grizzly',
    'Imrie',
    'John Day',
    'Keeler',
    'Lower Monumental',
    'Malin',
    'Marion',
    'Monroe',
    'North Bonneville',
    'Ostrander',
    'Paul',
    'Pearl',
    'Phalen Gulch',
    'Rock Creek',
    'Schultz',
    'Slatt',
    'Summer Lake',
    'Troutdale',
    'Wautoma']

SIGNALS = [
    'Allston 500 A1 SA - North Bus Voltage Mag',
    'Allston 500 A1 SA - North Bus Voltage Ang',
    'Allston 500 A1 SA - A phase North Bus Voltage Mag',
    'Allston 500 A1 SA - A phase North Bus Voltage Ang',
    'Allston 500 A1 SA - B phase North Bus Voltage Mag',
    'Allston 500 A1 SA - B phase North Bus Voltage Ang',
    'Allston 500 A1 SA - C phase North Bus Voltage Mag',
    'Allston 500 A1 SA - C phase North Bus Voltage Ang',
    'Allston 500 A1 SA - South Bus Voltage Mag',
    'Allston 500 A1 SA - South Bus Voltage Ang',
    'Allston 500 A1 SA - A phase South Bus Voltage Mag',
    'Allston 500 A1 SA - A phase South Bus Voltage Ang',
    'Allston 500 A1 SA - B phase South Bus Voltage Mag',
    'Allston 500 A1 SA - B phase South Bus Voltage Ang',
    'Allston 500 A1 SA - C phase South Bus Voltage Mag',
    'Allston 500 A1 SA - C phase South Bus Voltage Ang',
    'Allston 500 A1 SA - Napavine #1 Current Mag',
    'Allston 500 A1 SA - Napavine #1 Current Ang',
    'Allston 500 A1 SA - Keeler #1 Current Mag',
    'Allston 500 A1 SA - Keeler #1 Current Ang',
    'Allston 500 A1 SA - Paul #2 Current Mag',
    'Allston 500 A1 SA - Paul #2 Current Ang',
    'Allston 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Allston 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Allston 500 A1 SA - Xfmr Bank #2 Current Mag',
    'Allston 500 A1 SA - Xfmr Bank #2 Current Ang',
    'Allston 500 A1 SA Frequency',
    'Alvey 500 A1 SA - Alvey-Dixonville #1 Voltage Mag',
    'Alvey 500 A1 SA - Alvey-Dixonville #1 Voltage Ang',
    'Alvey 500 A1 SA - A phase Alvey-Dixonville #1 Voltage Mag',
    'Alvey 500 A1 SA - A phase Alvey-Dixonville #1 Voltage Ang',
    'Alvey 500 A1 SA - B phase Alvey-Dixonville #1 Voltage Mag',
    'Alvey 500 A1 SA - B phase Alvey-Dixonville #1 Voltage Ang',
    'Alvey 500 A1 SA - C phase Alvey-Dixonville #1 Voltage Mag',
    'Alvey 500 A1 SA - C phase Alvey-Dixonville #1 Voltage Ang',
    'Alvey 500 A1 SA - Alvey-Marion #1 Voltage Mag',
    'Alvey 500 A1 SA - Alvey-Marion #1 Voltage Ang',
    'Alvey 500 A1 SA - A phase Alvey-Marion #1 Voltage Mag',
    'Alvey 500 A1 SA - A phase Alvey-Marion #1 Voltage Ang',
    'Alvey 500 A1 SA - B phase Alvey-Marion #1 Voltage Mag',
    'Alvey 500 A1 SA - B phase Alvey-Marion #1 Voltage Ang',
    'Alvey 500 A1 SA - C phase Alvey-Marion #1 Voltage Mag',
    'Alvey 500 A1 SA - C phase Alvey-Marion #1 Voltage Ang',
    'Alvey 500 A1 SA - Marion #1 Current Mag',
    'Alvey 500 A1 SA - Marion #1 Current Ang',
    'Alvey 500 A1 SA - Dixonville #1 Current Mag',
    'Alvey 500 A1 SA - Dixonville #1 Current Ang',
    'Alvey 500 A1 SA - Xfmr Bank #5 Current Mag',
    'Alvey 500 A1 SA - Xfmr Bank #5 Current Ang',
    'Alvey 500 A1 SA Frequency',
    'Bell 230 A1 SA - Bus section #1 Voltage Mag',
    'Bell 230 A1 SA - Bus section #1 Voltage Ang',
    'Bell 230 A1 SA - A phase Bus section #1 Voltage Mag',
    'Bell 230 A1 SA - A phase Bus section #1 Voltage Ang',
    'Bell 230 A1 SA - B phase Bus section #1 Voltage Mag',
    'Bell 230 A1 SA - B phase Bus section #1 Voltage Ang',
    'Bell 230 A1 SA - C phase Bus section #1 Voltage Mag',
    'Bell 230 A1 SA - C phase Bus section #1 Voltage Ang',
    'Bell 230 A1 SA - Bus section #4 Voltage Mag',
    'Bell 230 A1 SA - Bus section #4 Voltage Ang',
    'Bell 230 A1 SA - A phase Bus section #4 Voltage Mag',
    'Bell 230 A1 SA - A phase Bus section #4 Voltage Ang',
    'Bell 230 A1 SA - B phase Bus section #4 Voltage Mag',
    'Bell 230 A1 SA - B phase Bus section #4 Voltage Ang',
    'Bell 230 A1 SA - C phase Bus section #4 Voltage Mag',
    'Bell 230 A1 SA - C phase Bus section #4 Voltage Ang',
    'Bell 230 A1 SA - Westside #1 Current Mag',
    'Bell 230 A1 SA - Westside #1 Current Ang',
    'Bell 230 A1 SA - Section #1 Bus tie Current Mag',
    'Bell 230 A1 SA - Section #1 Bus tie Current Ang',
    'Bell 230 A1 SA - Boundary #2 Current Mag',
    'Bell 230 A1 SA - Boundary #2 Current Ang',
    'Bell 230 A1 SA Frequency',
    'Bell 230 A2 SA - Bus section #2 Voltage Mag',
    'Bell 230 A2 SA - Bus section #2 Voltage Ang',
    'Bell 230 A2 SA - A phase Bus section #2 Voltage Mag',
    'Bell 230 A2 SA - A phase Bus section #2 Voltage Ang',
    'Bell 230 A2 SA - B phase Bus section #2 Voltage Mag',
    'Bell 230 A2 SA - B phase Bus section #2 Voltage Ang',
    'Bell 230 A2 SA - C phase Bus section #2 Voltage Mag',
    'Bell 230 A2 SA - C phase Bus section #2 Voltage Ang',
    'Bell 230 A2 SA - Bus section #3 Voltage Mag',
    'Bell 230 A2 SA - Bus section #3 Voltage Ang',
    'Bell 230 A2 SA - A phase Bus section #3 Voltage Mag',
    'Bell 230 A2 SA - A phase Bus section #3 Voltage Ang',
    'Bell 230 A2 SA - B phase Bus section #3 Voltage Mag',
    'Bell 230 A2 SA - B phase Bus section #3 Voltage Ang',
    'Bell 230 A2 SA - C phase Bus section #3 Voltage Mag',
    'Bell 230 A2 SA - C phase Bus section #3 Voltage Ang',
    'Bell 230 A2 SA - Section #2 Bus tie Current Mag',
    'Bell 230 A2 SA - Section #2 Bus tie Current Ang',
    'Bell 230 A2 SA - USK #1 Current Mag',
    'Bell 230 A2 SA - USK #1 Current Ang',
    'Bell 230 A2 SA - Xfmr Bank #6 Current Mag',
    'Bell 230 A2 SA - Xfmr Bank #6 Current Ang',
    'Bell 230 A2 SA - Section #3 Bus tie Current Mag',
    'Bell 230 A2 SA - Section #3 Bus tie Current Ang',
    'Bell 230 A2 SA - Lancaster #1 Current Mag',
    'Bell 230 A2 SA - Lancaster #1 Current Ang',
    'Bell 230 A2 SA - Boundary #3 Current Mag',
    'Bell 230 A2 SA - Boundary #3 Current Ang',
    'Bell 230 A2 SA Frequency',
    'Big Eddy 500 A1 SA - West Bus Voltage Mag',
    'Big Eddy 500 A1 SA - West Bus Voltage Ang',
    'Big Eddy 500 A1 SA - A phase West Bus Voltage Mag',
    'Big Eddy 500 A1 SA - A phase West Bus Voltage Ang',
    'Big Eddy 500 A1 SA - B phase West Bus Voltage Mag',
    'Big Eddy 500 A1 SA - B phase West Bus Voltage Ang',
    'Big Eddy 500 A1 SA - C phase West Bus Voltage Mag',
    'Big Eddy 500 A1 SA - C phase West Bus Voltage Ang',
    'Big Eddy 500 A1 SA - East Bus Voltage Mag',
    'Big Eddy 500 A1 SA - East Bus Voltage Ang',
    'Big Eddy 500 A1 SA - A phase East Bus Voltage Mag',
    'Big Eddy 500 A1 SA - A phase East Bus Voltage Ang',
    'Big Eddy 500 A1 SA - B phase East Bus Voltage Mag',
    'Big Eddy 500 A1 SA - B phase East Bus Voltage Ang',
    'Big Eddy 500 A1 SA - C phase East Bus Voltage Mag',
    'Big Eddy 500 A1 SA - C phase East Bus Voltage Ang',
    'Big Eddy 500 A1 SA - Celilo #1 Current Mag',
    'Big Eddy 500 A1 SA - Celilo #1 Current Ang',
    'Big Eddy 500 A1 SA - Ostrander #1 Current Mag',
    'Big Eddy 500 A1 SA - Ostrander #1 Current Ang',
    'Big Eddy 500 A1 SA - Celilo #2 Current Mag',
    'Big Eddy 500 A1 SA - Celilo #2 Current Ang',
    'Big Eddy 500 A1 SA Frequency',
    'Big Eddy 500 A2 SA - West Bus Voltage Mag',
    'Big Eddy 500 A2 SA - West Bus Voltage Ang',
    'Big Eddy 500 A2 SA - A phase West Bus Voltage Mag',
    'Big Eddy 500 A2 SA - A phase West Bus Voltage Ang',
    'Big Eddy 500 A2 SA - B phase West Bus Voltage Mag',
    'Big Eddy 500 A2 SA - B phase West Bus Voltage Ang',
    'Big Eddy 500 A2 SA - C phase West Bus Voltage Mag',
    'Big Eddy 500 A2 SA - C phase West Bus Voltage Ang',
    'Big Eddy 500 A2 SA - East Bus Voltage Mag',
    'Big Eddy 500 A2 SA - East Bus Voltage Ang',
    'Big Eddy 500 A2 SA - A phase East Bus Voltage Mag',
    'Big Eddy 500 A2 SA - A phase East Bus Voltage Ang',
    'Big Eddy 500 A2 SA - B phase East Bus Voltage Mag',
    'Big Eddy 500 A2 SA - B phase East Bus Voltage Ang',
    'Big Eddy 500 A2 SA - C phase East Bus Voltage Mag',
    'Big Eddy 500 A2 SA - C phase East Bus Voltage Ang',
    'Big Eddy 500 A2 SA - Knight #1 Current Mag',
    'Big Eddy 500 A2 SA - Knight #1 Current Ang',
    'Big Eddy 500 A2 SA - Xfmr Bank #5 Current Mag',
    'Big Eddy 500 A2 SA - Xfmr Bank #5 Current Ang',
    'Big Eddy 500 A2 SA - John Day #1 Current Mag',
    'Big Eddy 500 A2 SA - John Day #1 Current Ang',
    'Big Eddy 500 A2 SA - Xfmr Bank #2 Current Mag',
    'Big Eddy 500 A2 SA - Xfmr Bank #2 Current Ang',
    'Big Eddy 500 A2 SA - John Day #2 Current Mag',
    'Big Eddy 500 A2 SA - John Day #2 Current Ang',
    'Big Eddy 500 A2 SA Frequency',
    'Captain Jack 500 A1 SA - North Bus Voltage Mag',
    'Captain Jack 500 A1 SA - North Bus Voltage Ang',
    'Captain Jack 500 A1 SA - A phase North Bus Voltage Mag',
    'Captain Jack 500 A1 SA - A phase North Bus Voltage Ang',
    'Captain Jack 500 A1 SA - B phase North Bus Voltage Mag',
    'Captain Jack 500 A1 SA - B phase North Bus Voltage Ang',
    'Captain Jack 500 A1 SA - C phase North Bus Voltage Mag',
    'Captain Jack 500 A1 SA - C phase North Bus Voltage Ang',
    'Captain Jack 500 A1 SA - South Bus Voltage Mag',
    'Captain Jack 500 A1 SA - South Bus Voltage Ang',
    'Captain Jack 500 A1 SA - A phase South Bus Voltage Mag',
    'Captain Jack 500 A1 SA - A phase South Bus Voltage Ang',
    'Captain Jack 500 A1 SA - B phase South Bus Voltage Mag',
    'Captain Jack 500 A1 SA - B phase South Bus Voltage Ang',
    'Captain Jack 500 A1 SA - C phase South Bus Voltage Mag',
    'Captain Jack 500 A1 SA - C phase South Bus Voltage Ang',
    'Captain Jack 500 A1 SA - Grizzly #1 Current Mag',
    'Captain Jack 500 A1 SA - Grizzly #1 Current Ang',
    'Captain Jack 500 A1 SA - Malin #1 Current Mag',
    'Captain Jack 500 A1 SA - Malin #1 Current Ang',
    'Captain Jack 500 A1 SA - Klamath Falls Cogen #1 Current Mag',
    'Captain Jack 500 A1 SA - Klamath Falls Cogen #1 Current Ang',
    'Captain Jack 500 A1 SA - Malin #2 Current Mag',
    'Captain Jack 500 A1 SA - Malin #2 Current Ang',
    'Captain Jack 500 A1 SA - Olinda #1 Current Mag',
    'Captain Jack 500 A1 SA - Olinda #1 Current Ang',
    'Captain Jack 500 A1 SA - Reactor Grp #1 Current Mag',
    'Captain Jack 500 A1 SA - Reactor Grp #1 Current Ang',
    'Captain Jack 500 A1 SA Frequency',
    'Central Ferry 500 A1 SA - East Bus Voltage Mag',
    'Central Ferry 500 A1 SA - East Bus Voltage Ang',
    'Central Ferry 500 A1 SA - A phase East Bus Voltage Mag',
    'Central Ferry 500 A1 SA - A phase East Bus Voltage Ang',
    'Central Ferry 500 A1 SA - B phase East Bus Voltage Mag',
    'Central Ferry 500 A1 SA - B phase East Bus Voltage Ang',
    'Central Ferry 500 A1 SA - C phase East Bus Voltage Mag',
    'Central Ferry 500 A1 SA - C phase East Bus Voltage Ang',
    'Central Ferry 500 A1 SA - West Bus Voltage Mag',
    'Central Ferry 500 A1 SA - West Bus Voltage Ang',
    'Central Ferry 500 A1 SA - A phase West Bus Voltage Mag',
    'Central Ferry 500 A1 SA - A phase West Bus Voltage Ang',
    'Central Ferry 500 A1 SA - B phase West Bus Voltage Mag',
    'Central Ferry 500 A1 SA - B phase West Bus Voltage Ang',
    'Central Ferry 500 A1 SA - C phase West Bus Voltage Mag',
    'Central Ferry 500 A1 SA - C phase West Bus Voltage Ang',
    'Central Ferry 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Central Ferry 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Central Ferry 500 A1 SA - Lower Granite #2 Current Mag',
    'Central Ferry 500 A1 SA - Lower Granite #2 Current Ang',
    'Central Ferry 500 A1 SA - Little Goose #2 Current Mag',
    'Central Ferry 500 A1 SA - Little Goose #2 Current Ang',
    'Central Ferry 500 A1 SA Frequency',
    'Chief Joseph 230 A1 SA - Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A1 SA - Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A1 SA - A phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A1 SA - A phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A1 SA - B phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A1 SA - B phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A1 SA - C phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A1 SA - C phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A1 SA - Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A1 SA - Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A1 SA - A phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A1 SA - A phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A1 SA - B phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A1 SA - B phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A1 SA - C phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A1 SA - C phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A1 SA - Powerhouse #1 Current Mag',
    'Chief Joseph 230 A1 SA - Powerhouse #1 Current Ang',
    'Chief Joseph 230 A1 SA - Grand Coulee #2 Current Mag',
    'Chief Joseph 230 A1 SA - Grand Coulee #2 Current Ang',
    'Chief Joseph 230 A1 SA - Powerhouse #2 Current Mag',
    'Chief Joseph 230 A1 SA - Powerhouse #2 Current Ang',
    'Chief Joseph 230 A1 SA - Bus tie #1 Current Mag',
    'Chief Joseph 230 A1 SA - Bus tie #1 Current Ang',
    'Chief Joseph 230 A1 SA - Snohomish #3 Current Mag',
    'Chief Joseph 230 A1 SA - Snohomish #3 Current Ang',
    'Chief Joseph 230 A1 SA Frequency',
    'Chief Joseph 230 A2 SA - Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A2 SA - Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A2 SA - A phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A2 SA - A phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A2 SA - B phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A2 SA - B phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A2 SA - C phase Bus Section #1 Voltage Mag',
    'Chief Joseph 230 A2 SA - C phase Bus Section #1 Voltage Ang',
    'Chief Joseph 230 A2 SA - Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A2 SA - Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A2 SA - A phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A2 SA - A phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A2 SA - B phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A2 SA - B phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A2 SA - C phase Bus Section #2 Voltage Mag',
    'Chief Joseph 230 A2 SA - C phase Bus Section #2 Voltage Ang',
    'Chief Joseph 230 A2 SA - Grand Coulee #1 Current Mag',
    'Chief Joseph 230 A2 SA - Grand Coulee #1 Current Ang',
    'Chief Joseph 230 A2 SA - Powerhouse #3 Current Mag',
    'Chief Joseph 230 A2 SA - Powerhouse #3 Current Ang',
    'Chief Joseph 230 A2 SA - Braking resistor Current Mag',
    'Chief Joseph 230 A2 SA - Braking resistor Current Ang',
    'Chief Joseph 230 A2 SA - Bus tie #2 Current Mag',
    'Chief Joseph 230 A2 SA - Bus tie #2 Current Ang',
    'Chief Joseph 230 A2 SA - Snohomish #4 Current Mag',
    'Chief Joseph 230 A2 SA - Snohomish #4 Current Ang',
    'Chief Joseph 230 A2 SA - Powerhouse #4 Current Mag',
    'Chief Joseph 230 A2 SA - Powerhouse #4 Current Ang',
    'Chief Joseph 230 A2 SA Frequency',
    'Chief Joseph 500 A1 SA - East Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - East Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - A phase East Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - A phase East Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - B phase East Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - B phase East Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - C phase East Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - C phase East Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - West Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - West Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - A phase West Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - A phase West Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - B phase West Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - B phase West Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - C phase West Bus Voltage Mag',
    'Chief Joseph 500 A1 SA - C phase West Bus Voltage Ang',
    'Chief Joseph 500 A1 SA - Xfmr Bank #3 Current Mag',
    'Chief Joseph 500 A1 SA - Xfmr Bank #3 Current Ang',
    'Chief Joseph 500 A1 SA - Grand Coulee #3 Current Mag',
    'Chief Joseph 500 A1 SA - Grand Coulee #3 Current Ang',
    'Chief Joseph 500 A1 SA - Powerhouse #5 Current Mag',
    'Chief Joseph 500 A1 SA - Powerhouse #5 Current Ang',
    'Chief Joseph 500 A1 SA - Sickler #1 Current Mag',
    'Chief Joseph 500 A1 SA - Sickler #1 Current Ang',
    'Chief Joseph 500 A1 SA - Powerhouse #6 Current Mag',
    'Chief Joseph 500 A1 SA - Powerhouse #6 Current Ang',
    'Chief Joseph 500 A1 SA - Monroe #1 Current Mag',
    'Chief Joseph 500 A1 SA - Monroe #1 Current Ang',
    'Chief Joseph 500 A1 SA Frequency',
    'Custer 500 A1 SA - West Bus Voltage Mag',
    'Custer 500 A1 SA - West Bus Voltage Ang',
    'Custer 500 A1 SA - A phase West Bus Voltage Mag',
    'Custer 500 A1 SA - A phase West Bus Voltage Ang',
    'Custer 500 A1 SA - B phase West Bus Voltage Mag',
    'Custer 500 A1 SA - B phase West Bus Voltage Ang',
    'Custer 500 A1 SA - C phase West Bus Voltage Mag',
    'Custer 500 A1 SA - C phase West Bus Voltage Ang',
    'Custer 500 A1 SA - East Bus Voltage Mag',
    'Custer 500 A1 SA - East Bus Voltage Ang',
    'Custer 500 A1 SA - A phase East Bus Voltage Mag',
    'Custer 500 A1 SA - A phase East Bus Voltage Ang',
    'Custer 500 A1 SA - B phase East Bus Voltage Mag',
    'Custer 500 A1 SA - B phase East Bus Voltage Ang',
    'Custer 500 A1 SA - C phase East Bus Voltage Mag',
    'Custer 500 A1 SA - C phase East Bus Voltage Ang',
    'Custer 500 A1 SA - Monroe #2 Current Mag',
    'Custer 500 A1 SA - Monroe #2 Current Ang',
    'Custer 500 A1 SA - Ingledow #2 Current Mag',
    'Custer 500 A1 SA - Ingledow #2 Current Ang',
    'Custer 500 A1 SA - Ingledow #1 Current Mag',
    'Custer 500 A1 SA - Ingledow #1 Current Ang',
    'Custer 500 A1 SA - Monroe #1 Current Mag',
    'Custer 500 A1 SA - Monroe #1 Current Ang',
    'Custer 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Custer 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Custer 500 A1 SA - Xfmr Bank #2 Current Mag',
    'Custer 500 A1 SA - Xfmr Bank #2 Current Ang',
    'Custer 500 A1 SA Frequency',
    'Dodge Junction data PMU - 230 Main Bus Voltage Mag',
    'Dodge Junction data PMU - 230 Main Bus Voltage Ang',
    'Dodge Junction data PMU - A phase 230 Main Bus Voltage Mag',
    'Dodge Junction data PMU - A phase 230 Main Bus Voltage Ang',
    'Dodge Junction data PMU - B phase 230 Main Bus Voltage Mag',
    'Dodge Junction data PMU - B phase 230 Main Bus Voltage Ang',
    'Dodge Junction data PMU - C phase 230 Main Bus Voltage Mag',
    'Dodge Junction data PMU - C phase 230 Main Bus Voltage Ang',
    'Dodge Junction data PMU - 34.5 Main Bus Voltage Mag',
    'Dodge Junction data PMU - 34.5 Main Bus Voltage Ang',
    'Dodge Junction data PMU - A phase 34.5 Main Bus Voltage Mag',
    'Dodge Junction data PMU - A phase 34.5 Main Bus Voltage Ang',
    'Dodge Junction data PMU - B phase 34.5 Main Bus Voltage Mag',
    'Dodge Junction data PMU - B phase 34.5 Main Bus Voltage Ang',
    'Dodge Junction data PMU - C phase 34.5 Main Bus Voltage Mag',
    'Dodge Junction data PMU - C phase 34.5 Main Bus Voltage Ang',
    'Dodge Junction data PMU - 230kV main bus Current Mag',
    'Dodge Junction data PMU - 230kV main bus Current Ang',
    'Dodge Junction data PMU - 34.5kV main bus Current Mag',
    'Dodge Junction data PMU - 34.5kV main bus Current Ang',
    'Dodge Junction data PMU - 34.5kV reactor Current Mag',
    'Dodge Junction data PMU - 34.5kV reactor Current Ang',
    'Dodge Junction data PMU Frequency',
    'Dooley data PMU #1 - 230 Main bus Voltage Mag',
    'Dooley data PMU #1 - 230 Main bus Voltage Ang',
    'Dooley data PMU #1 - A phase 230 Main bus Voltage Mag',
    'Dooley data PMU #1 - A phase 230 Main bus Voltage Ang',
    'Dooley data PMU #1 - B phase 230 Main bus Voltage Mag',
    'Dooley data PMU #1 - B phase 230 Main bus Voltage Ang',
    'Dooley data PMU #1 - C phase 230 Main bus Voltage Mag',
    'Dooley data PMU #1 - C phase 230 Main bus Voltage Ang',
    'Dooley data PMU #1 - 230kV xfmr bank #1 Current Mag',
    'Dooley data PMU #1 - 230kV xfmr bank #1 Current Ang',
    'Dooley data PMU #1 - 230kV xfmr bank #2 Current Mag',
    'Dooley data PMU #1 - 230kV xfmr bank #2 Current Ang',
    'Dooley data PMU #1 Frequency',
    'Dooley data PMU #2 - 34.5 Bank #1 Voltage Mag',
    'Dooley data PMU #2 - 34.5 Bank #1 Voltage Ang',
    'Dooley data PMU #2 - A phase 34.5 Bank #1 Voltage Mag',
    'Dooley data PMU #2 - A phase 34.5 Bank #1 Voltage Ang',
    'Dooley data PMU #2 - B phase 34.5 Bank #1 Voltage Mag',
    'Dooley data PMU #2 - B phase 34.5 Bank #1 Voltage Ang',
    'Dooley data PMU #2 - C phase 34.5 Bank #1 Voltage Mag',
    'Dooley data PMU #2 - C phase 34.5 Bank #1 Voltage Ang',
    'Dooley data PMU #2 - 34.5 Bank #2 Voltage Mag',
    'Dooley data PMU #2 - 34.5 Bank #2 Voltage Ang',
    'Dooley data PMU #2 - A phase 34.5 Bank #2 Voltage Mag',
    'Dooley data PMU #2 - A phase 34.5 Bank #2 Voltage Ang',
    'Dooley data PMU #2 - B phase 34.5 Bank #3 Voltage Mag',
    'Dooley data PMU #2 - B phase 34.5 Bank #3 Voltage Ang',
    'Dooley data PMU #2 - C phase 34.5 Bank #2 Voltage Mag',
    'Dooley data PMU #2 - C phase 34.5 Bank #2 Voltage Ang',
    'Dooley data PMU #2 - Cap bank Current Mag',
    'Dooley data PMU #2 - Cap bank Current Ang',
    'Dooley data PMU #2 - Windy Flats #1 Current Mag',
    'Dooley data PMU #2 - Windy Flats #1 Current Ang',
    'Dooley data PMU #2 - 34.5 Bank #2 Current Mag',
    'Dooley data PMU #2 - 34.5 Bank #2 Current Ang',
    'Dooley data PMU #2 - Windy Flats #3 Current Mag',
    'Dooley data PMU #2 - Windy Flats #3 Current Ang',
    'Dooley data PMU #2 Frequency',
    'Echo Lake 500 A1 SA - North Bus Voltage Mag',
    'Echo Lake 500 A1 SA - North Bus Voltage Ang',
    'Echo Lake 500 A1 SA - A phase North Bus Voltage Mag',
    'Echo Lake 500 A1 SA - A phase North Bus Voltage Ang',
    'Echo Lake 500 A1 SA - B phase North Bus Voltage Mag',
    'Echo Lake 500 A1 SA - B phase North Bus Voltage Ang',
    'Echo Lake 500 A1 SA - C phase North Bus Voltage Mag',
    'Echo Lake 500 A1 SA - C phase North Bus Voltage Ang',
    'Echo Lake 500 A1 SA - South Bus Voltage Mag',
    'Echo Lake 500 A1 SA - South Bus Voltage Ang',
    'Echo Lake 500 A1 SA - A phase South Bus Voltage Mag',
    'Echo Lake 500 A1 SA - A phase South Bus Voltage Ang',
    'Echo Lake 500 A1 SA - B phase South Bus Voltage Mag',
    'Echo Lake 500 A1 SA - B phase South Bus Voltage Ang',
    'Echo Lake 500 A1 SA - C phase South Bus Voltage Mag',
    'Echo Lake 500 A1 SA - C phase South Bus Voltage Ang',
    'Echo Lake 500 A1 SA - Schultz #1 Current Mag',
    'Echo Lake 500 A1 SA - Schultz #1 Current Ang',
    'Echo Lake 500 A1 SA - Cap Grp #1 Current Mag',
    'Echo Lake 500 A1 SA - Cap Grp #1 Current Ang',
    'Echo Lake 500 A1 SA - Maple Valley #1 Current Mag',
    'Echo Lake 500 A1 SA - Maple Valley #1 Current Ang',
    'Echo Lake 500 A1 SA - Monroe #1 Current Mag',
    'Echo Lake 500 A1 SA - Monroe #1 Current Ang',
    'Echo Lake 500 A1 SA - Raver #1 Current Mag',
    'Echo Lake 500 A1 SA - Raver #1 Current Ang',
    'Echo Lake 500 A1 SA - Cap Grp #2 Current Mag',
    'Echo Lake 500 A1 SA - Cap Grp #2 Current Ang',
    'Echo Lake 500 A1 SA Frequency',
    'Garrison 500 A1 SA - East Bus Voltage Mag',
    'Garrison 500 A1 SA - East Bus Voltage Ang',
    'Garrison 500 A1 SA - A phase East Bus Voltage Mag',
    'Garrison 500 A1 SA - A phase East Bus Voltage Ang',
    'Garrison 500 A1 SA - B phase East Bus Voltage Mag',
    'Garrison 500 A1 SA - B phase East Bus Voltage Ang',
    'Garrison 500 A1 SA - C phase East Bus Voltage Mag',
    'Garrison 500 A1 SA - C phase East Bus Voltage Ang',
    'Garrison 500 A1 SA - West Bus Voltage Mag',
    'Garrison 500 A1 SA - West Bus Voltage Ang',
    'Garrison 500 A1 SA - A phase West Bus Voltage Mag',
    'Garrison 500 A1 SA - A phase West Bus Voltage Ang',
    'Garrison 500 A1 SA - B phase West Bus Voltage Mag',
    'Garrison 500 A1 SA - B phase West Bus Voltage Ang',
    'Garrison 500 A1 SA - C phase West Bus Voltage Mag',
    'Garrison 500 A1 SA - C phase West Bus Voltage Ang',
    'Garrison 500 A1 SA - Taft #1 Current Mag',
    'Garrison 500 A1 SA - Taft #1 Current Ang',
    'Garrison 500 A1 SA - Broadview #1 Current Mag',
    'Garrison 500 A1 SA - Broadview #1 Current Ang',
    'Garrison 500 A1 SA - Broadview #2 Current Mag',
    'Garrison 500 A1 SA - Broadview #2 Current Ang',
    'Garrison 500 A1 SA - Taft #2 Current Mag',
    'Garrison 500 A1 SA - Taft #2 Current Ang',
    'Garrison 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Garrison 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Garrison 500 A1 SA Frequency',
    'Grizzly 500 A1 SA - North Bus Voltage Mag',
    'Grizzly 500 A1 SA - North Bus Voltage Ang',
    'Grizzly 500 A1 SA - A phase North Bus Voltage Mag',
    'Grizzly 500 A1 SA - A phase North Bus Voltage Ang',
    'Grizzly 500 A1 SA - B phase North Bus Voltage Mag',
    'Grizzly 500 A1 SA - B phase North Bus Voltage Ang',
    'Grizzly 500 A1 SA - C phase North Bus Voltage Mag',
    'Grizzly 500 A1 SA - C phase North Bus Voltage Ang',
    'Grizzly 500 A1 SA - South Bus Voltage Mag',
    'Grizzly 500 A1 SA - South Bus Voltage Ang',
    'Grizzly 500 A1 SA - A phase South Bus Voltage Mag',
    'Grizzly 500 A1 SA - A phase South Bus Voltage Ang',
    'Grizzly 500 A1 SA - B phase South Bus Voltage Mag',
    'Grizzly 500 A1 SA - B phase South Bus Voltage Ang',
    'Grizzly 500 A1 SA - C phase South Bus Voltage Mag',
    'Grizzly 500 A1 SA - C phase South Bus Voltage Ang',
    'Grizzly 500 A1 SA - Buckley #1 Current Mag',
    'Grizzly 500 A1 SA - Buckley #1 Current Ang',
    'Grizzly 500 A1 SA - Summer Lake #1 Current Mag',
    'Grizzly 500 A1 SA - Summer Lake #1 Current Ang',
    'Grizzly 500 A1 SA - John Day #2 Current Mag',
    'Grizzly 500 A1 SA - John Day #2 Current Ang',
    'Grizzly 500 A1 SA - Malin #2 Current Mag',
    'Grizzly 500 A1 SA - Malin #2 Current Ang',
    'Grizzly 500 A1 SA - Captain Jack #1 Current Mag',
    'Grizzly 500 A1 SA - Captain Jack #1 Current Ang',
    'Grizzly 500 A1 SA - Reactor Bank #3 Current Mag',
    'Grizzly 500 A1 SA - Reactor Bank #3 Current Ang',
    'Grizzly 500 A1 SA Frequency',
    'Grizzly 500 A2 SA - North Bus Voltage Mag',
    'Grizzly 500 A2 SA - North Bus Voltage Ang',
    'Grizzly 500 A2 SA - A phase North Bus Voltage Mag',
    'Grizzly 500 A2 SA - A phase North Bus Voltage Ang',
    'Grizzly 500 A2 SA - B phase North Bus Voltage Mag',
    'Grizzly 500 A2 SA - B phase North Bus Voltage Ang',
    'Grizzly 500 A2 SA - C phase North Bus Voltage Mag',
    'Grizzly 500 A2 SA - C phase North Bus Voltage Ang',
    'Grizzly 500 A2 SA - South Bus Voltage Mag',
    'Grizzly 500 A2 SA - South Bus Voltage Ang',
    'Grizzly 500 A2 SA - A phase South Bus Voltage Mag',
    'Grizzly 500 A2 SA - A phase South Bus Voltage Ang',
    'Grizzly 500 A2 SA - B phase South Bus Voltage Mag',
    'Grizzly 500 A2 SA - B phase South Bus Voltage Ang',
    'Grizzly 500 A2 SA - C phase South Bus Voltage Mag',
    'Grizzly 500 A2 SA - C phase South Bus Voltage Ang',
    'Grizzly 500 A2 SA - John Day #1 Current Mag',
    'Grizzly 500 A2 SA - John Day #1 Current Ang',
    'Grizzly 500 A2 SA - Round Butte #1 Current Mag',
    'Grizzly 500 A2 SA - Round Butte #1 Current Ang',
    'Grizzly 500 A2 SA - Reactor Bank #1 Current Mag',
    'Grizzly 500 A2 SA - Reactor Bank #1 Current Ang',
    'Grizzly 500 A2 SA - Reactor Bank #2 Current Mag',
    'Grizzly 500 A2 SA - Reactor Bank #2 Current Ang',
    'Grizzly 500 A2 SA Frequency',
    'Imrie data PMU - 230 Main Bus Voltage Mag',
    'Imrie data PMU - 230 Main Bus Voltage Ang',
    'Imrie data PMU - A phase 230 Main Bus Voltage Mag',
    'Imrie data PMU - A phase 230 Main Bus Voltage Ang',
    'Imrie data PMU - B phase 230 Main Bus Voltage Mag',
    'Imrie data PMU - B phase 230 Main Bus Voltage Ang',
    'Imrie data PMU - C phase 230 Main Bus Voltage Mag',
    'Imrie data PMU - C phase 230 Main Bus Voltage Ang',
    'Imrie data PMU - 34.5 Main Bus Voltage Mag',
    'Imrie data PMU - 34.5 Main Bus Voltage Ang',
    'Imrie data PMU - A phase 34.5 Main Bus Voltage Mag',
    'Imrie data PMU - A phase 34.5 Main Bus Voltage Ang',
    'Imrie data PMU - B phase 34.5 Main Bus Voltage Mag',
    'Imrie data PMU - B phase 34.5 Main Bus Voltage Ang',
    'Imrie data PMU - C phase 34.5 Main Bus Voltage Mag',
    'Imrie data PMU - C phase 34.5 Main Bus Voltage Ang',
    'Imrie data PMU - 230kV transformer bank #1 Current Mag',
    'Imrie data PMU - 230kV transformer bank #1 Current Ang',
    'Imrie data PMU - 34.5kV main bus Current Mag',
    'Imrie data PMU - 34.5kV main bus Current Ang',
    'Imrie data PMU - 34.5kV reactor Current Mag',
    'Imrie data PMU - 34.5kV reactor Current Ang',
    'Imrie data PMU Frequency',
    'John Day 230 A1 SA - West Bus Voltage Mag',
    'John Day 230 A1 SA - West Bus Voltage Ang',
    'John Day 230 A1 SA - A phase West Bus Voltage Mag',
    'John Day 230 A1 SA - A phase West Bus Voltage Ang',
    'John Day 230 A1 SA - B phase West Bus Voltage Mag',
    'John Day 230 A1 SA - B phase West Bus Voltage Ang',
    'John Day 230 A1 SA - C phase West Bus Voltage Mag',
    'John Day 230 A1 SA - C phase West Bus Voltage Ang',
    'John Day 230 A1 SA - Xfmr Bank #1 Voltage Mag',
    'John Day 230 A1 SA - Xfmr Bank #1 Voltage Ang',
    'John Day 230 A1 SA - A phase West Xfmr Bank #1 Voltage Mag',
    'John Day 230 A1 SA - A phase West Xfmr Bank #1 Voltage Ang',
    'John Day 230 A1 SA - B phase West Xfmr Bank #1 Voltage Mag',
    'John Day 230 A1 SA - B phase West Xfmr Bank #1 Voltage Ang',
    'John Day 230 A1 SA - C phase West Xfmr Bank #1 Voltage Mag',
    'John Day 230 A1 SA - C phase West Xfmr Bank #1 Voltage Ang',
    'John Day 230 A1 SA - Biglow Canyon #1 Current Mag',
    'John Day 230 A1 SA - Biglow Canyon #1 Current Ang',
    'John Day 230 A1 SA - Xfmr Bank #1 Current Mag',
    'John Day 230 A1 SA - Xfmr Bank #1 Current Ang',
    'John Day 230 A1 SA - Reactor Group #2 section 1 Current Mag',
    'John Day 230 A1 SA - Reactor Group #2 section 1 Current Ang',
    'John Day 230 A1 SA - Reactor Group #2 section 2 Current Mag',
    'John Day 230 A1 SA - Reactor Group #2 section 2 Current Ang',
    'John Day 230 A1 SA - Klondike Schoolhouse #1 Current Mag',
    'John Day 230 A1 SA - Klondike Schoolhouse #1 Current Ang',
    'John Day 230 A1 SA Frequency',
    'John Day 500 A1 SA - East Bus Voltage Mag',
    'John Day 500 A1 SA - East Bus Voltage Ang',
    'John Day 500 A1 SA - A phase East Bus Voltage Mag',
    'John Day 500 A1 SA - A phase East Bus Voltage Ang',
    'John Day 500 A1 SA - B phase East Bus Voltage Mag',
    'John Day 500 A1 SA - B phase East Bus Voltage Ang',
    'John Day 500 A1 SA - C phase East Bus Voltage Mag',
    'John Day 500 A1 SA - C phase East Bus Voltage Ang',
    'John Day 500 A1 SA - West Bus Voltage Mag',
    'John Day 500 A1 SA - West Bus Voltage Ang',
    'John Day 500 A1 SA - A phase West Bus Voltage Mag',
    'John Day 500 A1 SA - A phase West Bus Voltage Ang',
    'John Day 500 A1 SA - B phase West Bus Voltage Mag',
    'John Day 500 A1 SA - B phase West Bus Voltage Ang',
    'John Day 500 A1 SA - C phase West Bus Voltage Mag',
    'John Day 500 A1 SA - C phase West Bus Voltage Ang',
    'John Day 500 A1 SA - Slatt #1 Current Mag',
    'John Day 500 A1 SA - Slatt #1 Current Ang',
    'John Day 500 A1 SA - Grizzly #2 Current Mag',
    'John Day 500 A1 SA - Grizzly #2 Current Ang',
    'John Day 500 A1 SA - Powerhouse #1 Current Mag',
    'John Day 500 A1 SA - Powerhouse #1 Current Ang',
    'John Day 500 A1 SA - Grizzly #1 Current Mag',
    'John Day 500 A1 SA - Grizzly #1 Current Ang',
    'John Day 500 A1 SA - Powerhouse #2 Current Mag',
    'John Day 500 A1 SA - Powerhouse #2 Current Ang',
    'John Day 500 A1 SA - Powerhouse #3 Current Mag',
    'John Day 500 A1 SA - Powerhouse #3 Current Ang',
    'John Day 500 A1 SA Frequency',
    'John Day 500 A2 SA - East Bus Voltage Mag',
    'John Day 500 A2 SA - East Bus Voltage Ang',
    'John Day 500 A2 SA - A phase East Bus Voltage Mag',
    'John Day 500 A2 SA - A phase East Bus Voltage Ang',
    'John Day 500 A2 SA - B phase East Bus Voltage Mag',
    'John Day 500 A2 SA - B phase East Bus Voltage Ang',
    'John Day 500 A2 SA - C phase East Bus Voltage Mag',
    'John Day 500 A2 SA - C phase East Bus Voltage Ang',
    'John Day 500 A2 SA - West Bus Voltage Mag',
    'John Day 500 A2 SA - West Bus Voltage Ang',
    'John Day 500 A2 SA - A phase West Bus Voltage Mag',
    'John Day 500 A2 SA - A phase West Bus Voltage Ang',
    'John Day 500 A2 SA - B phase West Bus Voltage Mag',
    'John Day 500 A2 SA - B phase West Bus Voltage Ang',
    'John Day 500 A2 SA - C phase West Bus Voltage Mag',
    'John Day 500 A2 SA - C phase West Bus Voltage Ang',
    'John Day 500 A2 SA - Marion #1 Current Mag',
    'John Day 500 A2 SA - Marion #1 Current Ang',
    'John Day 500 A2 SA - Powerhouse #4 Current Mag',
    'John Day 500 A2 SA - Powerhouse #4 Current Ang',
    'John Day 500 A2 SA - Big Eddy #2 Current Mag',
    'John Day 500 A2 SA - Big Eddy #2 Current Ang',
    'John Day 500 A2 SA - McNary #2 Current Mag',
    'John Day 500 A2 SA - McNary #2 Current Ang',
    'John Day 500 A2 SA - Rock Creek #1 Current Mag',
    'John Day 500 A2 SA - Rock Creek #1 Current Ang',
    'John Day 500 A2 SA - Big Eddy #1 Current Mag',
    'John Day 500 A2 SA - Big Eddy #1 Current Ang',
    'John Day 500 A2 SA Frequency',
    'Keeler 230 A1 SA - 230 Main Bus Voltage Mag',
    'Keeler 230 A1 SA - 230 Main Bus Voltage Ang',
    'Keeler 230 A1 SA - A phase 230 Main Bus Voltage Mag',
    'Keeler 230 A1 SA - A phase 230 Main Bus Voltage Ang',
    'Keeler 230 A1 SA - B phase 230 Main Bus Voltage Mag',
    'Keeler 230 A1 SA - B phase 230 Main Bus Voltage Ang',
    'Keeler 230 A1 SA - C phase 230 Main Bus Voltage Mag',
    'Keeler 230 A1 SA - C phase 230 Main Bus Voltage Ang',
    'Keeler 230 A1 SA - Rivergate #1 Current Mag',
    'Keeler 230 A1 SA - Rivergate #1 Current Ang',
    'Keeler 230 A1 SA - Horizon #1 Current Mag',
    'Keeler 230 A1 SA - Horizon #1 Current Ang',
    'Keeler 230 A1 SA - Bus Tie Current Mag',
    'Keeler 230 A1 SA - Bus Tie Current Ang',
    "Keeler 230 A1 SA - St. Mary's Current Mag",
    "Keeler 230 A1 SA - St. Mary's Current Ang",
    'Keeler 230 A1 SA - SVC Current Mag',
    'Keeler 230 A1 SA - SVC Current Ang',
    'Keeler 230 A1 SA - Reactive Grp #2 Current Mag',
    'Keeler 230 A1 SA - Reactive Grp #2 Current Ang',
    'Keeler 230 A1 SA Frequency',
    'Keeler 230 A2 SA - 230 Main Bus Voltage Mag',
    'Keeler 230 A2 SA - 230 Main Bus Voltage Ang',
    'Keeler 230 A2 SA - A phase 230 Main Bus Voltage Mag',
    'Keeler 230 A2 SA - A phase 230 Main Bus Voltage Ang',
    'Keeler 230 A2 SA - B phase 230 Main Bus Voltage Mag',
    'Keeler 230 A2 SA - B phase 230 Main Bus Voltage Ang',
    'Keeler 230 A2 SA - C phase 230 Main Bus Voltage Mag',
    'Keeler 230 A2 SA - C phase 230 Main Bus Voltage Ang',
    'Keeler 230 A2 SA - Xfmr Bank #1 Current Mag',
    'Keeler 230 A2 SA - Xfmr Bank #1 Current Ang',
    'Keeler 230 A2 SA - Xfmr Bank #2 Current Mag',
    'Keeler 230 A2 SA - Xfmr Bank #2 Current Ang',
    'Keeler 230 A2 SA - Bus Tie Current Mag',
    'Keeler 230 A2 SA - Bus Tie Current Ang',
    'Keeler 230 A2 SA - Xfmr Bank #3 Current Mag',
    'Keeler 230 A2 SA - Xfmr Bank #3 Current Ang',
    'Keeler 230 A2 SA Frequency',
    'Keeler 500 A1 SA - West Bus Voltage Mag',
    'Keeler 500 A1 SA - West Bus Voltage Ang',
    'Keeler 500 A1 SA - A phase West Bus Voltage Mag',
    'Keeler 500 A1 SA - A phase West Bus Voltage Ang',
    'Keeler 500 A1 SA - B phase West Bus Voltage Mag',
    'Keeler 500 A1 SA - B phase West Bus Voltage Ang',
    'Keeler 500 A1 SA - C phase West Bus Voltage Mag',
    'Keeler 500 A1 SA - C phase West Bus Voltage Ang',
    'Keeler 500 A1 SA - Allston #1 Voltage Mag',
    'Keeler 500 A1 SA - Allston #1 Voltage Ang',
    'Keeler 500 A1 SA - A phase Allston #1 Voltage Mag',
    'Keeler 500 A1 SA - A phase Allston #1 Voltage Ang',
    'Keeler 500 A1 SA - B phase Allston #1 Voltage Mag',
    'Keeler 500 A1 SA - B phase Allston #1 Voltage Ang',
    'Keeler 500 A1 SA - C phase Allston #1 Voltage Mag',
    'Keeler 500 A1 SA - C phase Allston #1 Voltage Ang',
    'Keeler 500 A1 SA - Xfmr Bank #2 Current Mag',
    'Keeler 500 A1 SA - Xfmr Bank #2 Current Ang',
    'Keeler 500 A1 SA - Allston #1 Current Mag',
    'Keeler 500 A1 SA - Allston #1 Current Ang',
    'Keeler 500 A1 SA - Pearl #1 Current Mag',
    'Keeler 500 A1 SA - Pearl #1 Current Ang',
    'Keeler 500 A1 SA - Cap Grp #3 Current Mag',
    'Keeler 500 A1 SA - Cap Grp #3 Current Ang',
    'Keeler 500 A1 SA Frequency',
    'Lower Monumental 500 A1 SA - Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - A phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - A phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - B phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - B phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - C phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - C phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - McNary #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - McNary #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - A phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - A phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - B phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - B phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - C phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A1 SA - C phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A1 SA - Powerhouse #1 Current Mag',
    'Lower Monumental 500 A1 SA - Powerhouse #1 Current Ang',
    'Lower Monumental 500 A1 SA - Little Goose #2 Current Mag',
    'Lower Monumental 500 A1 SA - Little Goose #2 Current Ang',
    'Lower Monumental 500 A1 SA - McNary #1 Current Mag',
    'Lower Monumental 500 A1 SA - McNary #1 Current Ang',
    'Lower Monumental 500 A1 SA - Little Goose #1 Current Mag',
    'Lower Monumental 500 A1 SA - Little Goose #1 Current Ang',
    'Lower Monumental 500 A1 SA Frequency',
    'Lower Monumental 500 A2 SA - Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - A phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - A phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - B phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - B phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - C phase Powerhouse #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - C phase Powerhouse #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - McNary #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - McNary #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - A phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - A phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - B phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - B phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - C phase McNary #1 Voltage Mag',
    'Lower Monumental 500 A2 SA - C phase McNary #1 Voltage Ang',
    'Lower Monumental 500 A2 SA - Hanford #1 Current Mag',
    'Lower Monumental 500 A2 SA - Hanford #1 Current Ang',
    'Lower Monumental 500 A2 SA - Ashe #1 Current Mag',
    'Lower Monumental 500 A2 SA - Ashe #1 Current Ang',
    'Lower Monumental 500 A2 SA - Reactor bank #1 Current Mag',
    'Lower Monumental 500 A2 SA - Reactor bank #1 Current Ang',
    'Lower Monumental 500 A2 SA Frequency',
    'Malin 500 A1 SA - North Bus Voltage Mag',
    'Malin 500 A1 SA - North Bus Voltage Ang',
    'Malin 500 A1 SA - A phase North Bus Voltage Mag',
    'Malin 500 A1 SA - A phase North Bus Voltage Ang',
    'Malin 500 A1 SA - B phase North Bus Voltage Mag',
    'Malin 500 A1 SA - B phase North Bus Voltage Ang',
    'Malin 500 A1 SA - C phase North Bus Voltage Mag',
    'Malin 500 A1 SA - C phase North Bus Voltage Ang',
    'Malin 500 A1 SA - South Bus Voltage Mag',
    'Malin 500 A1 SA - South Bus Voltage Ang',
    'Malin 500 A1 SA - A phase South Bus Voltage Mag',
    'Malin 500 A1 SA - A phase South Bus Voltage Ang',
    'Malin 500 A1 SA - B phase South Bus Voltage Mag',
    'Malin 500 A1 SA - B phase South Bus Voltage Ang',
    'Malin 500 A1 SA - C phase South Bus Voltage Mag',
    'Malin 500 A1 SA - C phase South Bus Voltage Ang',
    'Malin 500 A1 SA - Grizzly #2 Current Mag',
    'Malin 500 A1 SA - Grizzly #2 Current Ang',
    'Malin 500 A1 SA - Round Mountain #2 Current Mag',
    'Malin 500 A1 SA - Round Mountain #2 Current Ang',
    'Malin 500 A1 SA - Captain Jack #2 Current Mag',
    'Malin 500 A1 SA - Captain Jack #2 Current Ang',
    'Malin 500 A1 SA - Summer Lake #1 Current Mag',
    'Malin 500 A1 SA - Summer Lake #1 Current Ang',
    'Malin 500 A1 SA Frequency',
    'Malin 500 A2 SA - North Bus Voltage Mag',
    'Malin 500 A2 SA - North Bus Voltage Ang',
    'Malin 500 A2 SA - A phase North Bus Voltage Mag',
    'Malin 500 A2 SA - A phase North Bus Voltage Ang',
    'Malin 500 A2 SA - B phase North Bus Voltage Mag',
    'Malin 500 A2 SA - B phase North Bus Voltage Ang',
    'Malin 500 A2 SA - C phase North Bus Voltage Mag',
    'Malin 500 A2 SA - C phase North Bus Voltage Ang',
    'Malin 500 A2 SA - South Bus Voltage Mag',
    'Malin 500 A2 SA - South Bus Voltage Ang',
    'Malin 500 A2 SA - A phase South Bus Voltage Mag',
    'Malin 500 A2 SA - A phase South Bus Voltage Ang',
    'Malin 500 A2 SA - B phase South Bus Voltage Mag',
    'Malin 500 A2 SA - B phase South Bus Voltage Ang',
    'Malin 500 A2 SA - C phase South Bus Voltage Mag',
    'Malin 500 A2 SA - C phase South Bus Voltage Ang',
    'Malin 500 A2 SA - Captain Jack #1 Current Mag',
    'Malin 500 A2 SA - Captain Jack #1 Current Ang',
    'Malin 500 A2 SA - Round Mountain #1 Current Mag',
    'Malin 500 A2 SA - Round Mountain #1 Current Ang',
    'Malin 500 A2 SA - Xfmr Bank #1 Current Mag',
    'Malin 500 A2 SA - Xfmr Bank #1 Current Ang',
    'Malin 500 A2 SA Frequency',
    'Marion 500 A1 SA - North Bus Voltage Mag',
    'Marion 500 A1 SA - North Bus Voltage Ang',
    'Marion 500 A1 SA - A phase North Bus Voltage Mag',
    'Marion 500 A1 SA - A phase North Bus Voltage Ang',
    'Marion 500 A1 SA - B phase North Bus Voltage Mag',
    'Marion 500 A1 SA - B phase North Bus Voltage Ang',
    'Marion 500 A1 SA - C phase North Bus Voltage Mag',
    'Marion 500 A1 SA - C phase North Bus Voltage Ang',
    'Marion 500 A1 SA - South Bus Voltage Mag',
    'Marion 500 A1 SA - South Bus Voltage Ang',
    'Marion 500 A1 SA - A phase South Bus Voltage Mag',
    'Marion 500 A1 SA - A phase South Bus Voltage Ang',
    'Marion 500 A1 SA - B phase South Bus Voltage Mag',
    'Marion 500 A1 SA - B phase South Bus Voltage Ang',
    'Marion 500 A1 SA - C phase South Bus Voltage Mag',
    'Marion 500 A1 SA - C phase South Bus Voltage Ang',
    'Marion 500 A1 SA - Pearl #1 Current Mag',
    'Marion 500 A1 SA - Pearl #1 Current Ang',
    'Marion 500 A1 SA - Alvey #1 Current Mag',
    'Marion 500 A1 SA - Alvey #1 Current Ang',
    'Marion 500 A1 SA - Lane #1 Current Mag',
    'Marion 500 A1 SA - Lane #1 Current Ang',
    'Marion 500 A1 SA - Santiam #1 Current Mag',
    'Marion 500 A1 SA - Santiam #1 Current Ang',
    'Marion 500 A1 SA Frequency',
    'Marion 500 A2 SA - North Bus Voltage Mag',
    'Marion 500 A2 SA - North Bus Voltage Ang',
    'Marion 500 A2 SA - A phase North Bus Voltage Mag',
    'Marion 500 A2 SA - A phase North Bus Voltage Ang',
    'Marion 500 A2 SA - B phase North Bus Voltage Mag',
    'Marion 500 A2 SA - B phase North Bus Voltage Ang',
    'Marion 500 A2 SA - C phase North Bus Voltage Mag',
    'Marion 500 A2 SA - C phase North Bus Voltage Ang',
    'Marion 500 A2 SA - South Bus Voltage Mag',
    'Marion 500 A2 SA - South Bus Voltage Ang',
    'Marion 500 A2 SA - A phase South Bus Voltage Mag',
    'Marion 500 A2 SA - A phase South Bus Voltage Ang',
    'Marion 500 A2 SA - B phase South Bus Voltage Mag',
    'Marion 500 A2 SA - B phase South Bus Voltage Ang',
    'Marion 500 A2 SA - C phase South Bus Voltage Mag',
    'Marion 500 A2 SA - C phase South Bus Voltage Ang',
    'Marion 500 A2 SA - John Day #1 Current Mag',
    'Marion 500 A2 SA - John Day #1 Current Ang',
    'Marion 500 A2 SA - Buckley #1 Current Mag',
    'Marion 500 A2 SA - Buckley #1 Current Ang',
    'Marion 500 A2 SA - Ashe #2 Current Mag',
    'Marion 500 A2 SA - Ashe #2 Current Ang',
    'Marion 500 A2 SA Frequency',
    'Monroe 500 A1 SA - North Bus Voltage Mag',
    'Monroe 500 A1 SA - North Bus Voltage Ang',
    'Monroe 500 A1 SA - A phase North Bus Voltage Mag',
    'Monroe 500 A1 SA - A phase North Bus Voltage Ang',
    'Monroe 500 A1 SA - B phase North Bus Voltage Mag',
    'Monroe 500 A1 SA - B phase North Bus Voltage Ang',
    'Monroe 500 A1 SA - C phase North Bus Voltage Mag',
    'Monroe 500 A1 SA - C phase North Bus Voltage Ang',
    'Monroe 500 A1 SA - South Bus Voltage Mag',
    'Monroe 500 A1 SA - South Bus Voltage Ang',
    'Monroe 500 A1 SA - A phase South Bus Voltage Mag',
    'Monroe 500 A1 SA - A phase South Bus Voltage Ang',
    'Monroe 500 A1 SA - B phase South Bus Voltage Mag',
    'Monroe 500 A1 SA - B phase South Bus Voltage Ang',
    'Monroe 500 A1 SA - C phase South Bus Voltage Mag',
    'Monroe 500 A1 SA - C phase South Bus Voltage Ang',
    'Monroe 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Monroe 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Monroe 500 A1 SA - Custer #1 Current Mag',
    'Monroe 500 A1 SA - Custer #1 Current Ang',
    'Monroe 500 A1 SA - Custer #2 Current Mag',
    'Monroe 500 A1 SA - Custer #2 Current Ang',
    'Monroe 500 A1 SA - Echo Lake #1 Current Mag',
    'Monroe 500 A1 SA - Echo Lake #1 Current Ang',
    'Monroe 500 A1 SA - Chief Joseph #1 Current Mag',
    'Monroe 500 A1 SA - Chief Joseph #1 Current Ang',
    'Monroe 500 A1 SA Frequency',
    'North Bonneville 230 A1 SA - East Bus Voltage Mag',
    'North Bonneville 230 A1 SA - East Bus Voltage Ang',
    'North Bonneville 230 A1 SA - A phase East Bus Voltage Mag',
    'North Bonneville 230 A1 SA - A phase East Bus Voltage Ang',
    'North Bonneville 230 A1 SA - B phase East Bus Voltage Mag',
    'North Bonneville 230 A1 SA - B phase East Bus Voltage Ang',
    'North Bonneville 230 A1 SA - C phase East Bus Voltage Mag',
    'North Bonneville 230 A1 SA - C phase East Bus Voltage Ang',
    'North Bonneville 230 A1 SA - West Bus Voltage Mag',
    'North Bonneville 230 A1 SA - West Bus Voltage Ang',
    'North Bonneville 230 A1 SA - A phase West Bus Voltage Mag',
    'North Bonneville 230 A1 SA - A phase West Bus Voltage Ang',
    'North Bonneville 230 A1 SA - B phase West Bus Voltage Mag',
    'North Bonneville 230 A1 SA - B phase West Bus Voltage Ang',
    'North Bonneville 230 A1 SA - C phase West Bus Voltage Mag',
    'North Bonneville 230 A1 SA - C phase West Bus Voltage Ang',
    'North Bonneville 230 A1 SA - Bonneville #1 Current Mag',
    'North Bonneville 230 A1 SA - Bonneville #1 Current Ang',
    'North Bonneville 230 A1 SA - Bonneville #2 Current Mag',
    'North Bonneville 230 A1 SA - Bonneville #2 Current Ang',
    'North Bonneville 230 A1 SA - Bonneville #3 Current Mag',
    'North Bonneville 230 A1 SA - Bonneville #3 Current Ang',
    'North Bonneville 230 A1 SA - Bonneville #4 Current Mag',
    'North Bonneville 230 A1 SA - Bonneville #4 Current Ang',
    'North Bonneville 230 A1 SA - Bus Tie Current Mag',
    'North Bonneville 230 A1 SA - Bus Tie Current Ang',
    'North Bonneville 230 A1 SA Frequency',
    'North Bonneville 230 A2 SA - East Bus Voltage Mag',
    'North Bonneville 230 A2 SA - East Bus Voltage Ang',
    'North Bonneville 230 A2 SA - A phase East Bus Voltage Mag',
    'North Bonneville 230 A2 SA - A phase East Bus Voltage Ang',
    'North Bonneville 230 A2 SA - B phase East Bus Voltage Mag',
    'North Bonneville 230 A2 SA - B phase East Bus Voltage Ang',
    'North Bonneville 230 A2 SA - C phase East Bus Voltage Mag',
    'North Bonneville 230 A2 SA - C phase East Bus Voltage Ang',
    'North Bonneville 230 A2 SA - West Bus Voltage Mag',
    'North Bonneville 230 A2 SA - West Bus Voltage Ang',
    'North Bonneville 230 A2 SA - A phase West Bus Voltage Mag',
    'North Bonneville 230 A2 SA - A phase West Bus Voltage Ang',
    'North Bonneville 230 A2 SA - B phase West Bus Voltage Mag',
    'North Bonneville 230 A2 SA - B phase West Bus Voltage Ang',
    'North Bonneville 230 A2 SA - C phase West Bus Voltage Mag',
    'North Bonneville 230 A2 SA - C phase West Bus Voltage Ang',
    'North Bonneville 230 A2 SA - Troutdale #1 Current Mag',
    'North Bonneville 230 A2 SA - Troutdale #1 Current Ang',
    'North Bonneville 230 A2 SA - Troutdale #2 Current Mag',
    'North Bonneville 230 A2 SA - Troutdale #2 Current Ang',
    'North Bonneville 230 A2 SA - Ross #1 Current Mag',
    'North Bonneville 230 A2 SA - Ross #1 Current Ang',
    'North Bonneville 230 A2 SA - Ross #2 Current Mag',
    'North Bonneville 230 A2 SA - Ross #2 Current Ang',
    'North Bonneville 230 A2 SA - Midway #1 Current Mag',
    'North Bonneville 230 A2 SA - Midway #1 Current Ang',
    'North Bonneville 230 A2 SA - Bus tie Current Mag',
    'North Bonneville 230 A2 SA - Bus tie Current Ang',
    'North Bonneville 230 A2 SA Frequency',
    'Ostrander 500 A1 SA - East Bus Voltage Mag',
    'Ostrander 500 A1 SA - East Bus Voltage Ang',
    'Ostrander 500 A1 SA - A phase East Bus Voltage Mag',
    'Ostrander 500 A1 SA - A phase East Bus Voltage Ang',
    'Ostrander 500 A1 SA - B phase East Bus Voltage Mag',
    'Ostrander 500 A1 SA - B phase East Bus Voltage Ang',
    'Ostrander 500 A1 SA - C phase East Bus Voltage Mag',
    'Ostrander 500 A1 SA - C phase East Bus Voltage Ang',
    'Ostrander 500 A1 SA - West Bus Voltage Mag',
    'Ostrander 500 A1 SA - West Bus Voltage Ang',
    'Ostrander 500 A1 SA - A phase West Bus Voltage Mag',
    'Ostrander 500 A1 SA - A phase West Bus Voltage Ang',
    'Ostrander 500 A1 SA - B phase West Bus Voltage Mag',
    'Ostrander 500 A1 SA - B phase West Bus Voltage Ang',
    'Ostrander 500 A1 SA - C phase West Bus Voltage Mag',
    'Ostrander 500 A1 SA - C phase West Bus Voltage Ang',
    'Ostrander 500 A1 SA - Troutdale #1 Current Mag',
    'Ostrander 500 A1 SA - Troutdale #1 Current Ang',
    'Ostrander 500 A1 SA - Knight #1 Current Mag',
    'Ostrander 500 A1 SA - Knight #1 Current Ang',
    'Ostrander 500 A1 SA - McLoughlin #1 Current Mag',
    'Ostrander 500 A1 SA - McLoughlin #1 Current Ang',
    'Ostrander 500 A1 SA - Big Eddy #1 Current Mag',
    'Ostrander 500 A1 SA - Big Eddy #1 Current Ang',
    'Ostrander 500 A1 SA - Pearl #1 Current Mag',
    'Ostrander 500 A1 SA - Pearl #1 Current Ang',
    'Ostrander 500 A1 SA Frequency',
    'Paul 500 A1 SA - North Bus Voltage Mag',
    'Paul 500 A1 SA - North Bus Voltage Ang',
    'Paul 500 A1 SA - A phase North Bus Voltage Mag',
    'Paul 500 A1 SA - A phase North Bus Voltage Ang',
    'Paul 500 A1 SA - B phase North Bus Voltage Mag',
    'Paul 500 A1 SA - B phase North Bus Voltage Ang',
    'Paul 500 A1 SA - C phase North Bus Voltage Mag',
    'Paul 500 A1 SA - C phase North Bus Voltage Ang',
    'Paul 500 A1 SA - South Bus Voltage Mag',
    'Paul 500 A1 SA - South Bus Voltage Ang',
    'Paul 500 A1 SA - A phase South Bus Voltage Mag',
    'Paul 500 A1 SA - A phase South Bus Voltage Ang',
    'Paul 500 A1 SA - B phase South Bus Voltage Mag',
    'Paul 500 A1 SA - B phase South Bus Voltage Ang',
    'Paul 500 A1 SA - C phase South Bus Voltage Mag',
    'Paul 500 A1 SA - C phase South Bus Voltage Ang',
    'Paul 500 A1 SA - Centralia Thermal PH #2 Current Mag',
    'Paul 500 A1 SA - Centralia Thermal PH #2 Current Ang',
    'Paul 500 A1 SA - Raver Current Mag',
    'Paul 500 A1 SA - Raver Current Ang',
    'Paul 500 A1 SA - Centralia Thermal PH #1 Current Mag',
    'Paul 500 A1 SA - Centralia Thermal PH #1 Current Ang',
    'Paul 500 A1 SA - Napavine Current Mag',
    'Paul 500 A1 SA - Napavine Current Ang',
    'Paul 500 A1 SA - Olympia Current Mag',
    'Paul 500 A1 SA - Olympia Current Ang',
    'Paul 500 A1 SA - Allston #2 Current Mag',
    'Paul 500 A1 SA - Allston #2 Current Ang',
    'Paul 500 A1 SA Frequency',
    'Paul 500 A2 SA - North Bus Voltage Mag',
    'Paul 500 A2 SA - North Bus Voltage Ang',
    'Paul 500 A2 SA - A phase North Bus Voltage Mag',
    'Paul 500 A2 SA - A phase North Bus Voltage Ang',
    'Paul 500 A2 SA - B phase North Bus Voltage Mag',
    'Paul 500 A2 SA - B phase North Bus Voltage Ang',
    'Paul 500 A2 SA - C phase North Bus Voltage Mag',
    'Paul 500 A2 SA - C phase North Bus Voltage Ang',
    'Paul 500 A2 SA - South Bus Voltage Mag',
    'Paul 500 A2 SA - South Bus Voltage Ang',
    'Paul 500 A2 SA - A phase South Bus Voltage Mag',
    'Paul 500 A2 SA - A phase South Bus Voltage Ang',
    'Paul 500 A2 SA - B phase South Bus Voltage Mag',
    'Paul 500 A2 SA - B phase South Bus Voltage Ang',
    'Paul 500 A2 SA - C phase South Bus Voltage Mag',
    'Paul 500 A2 SA - C phase South Bus Voltage Ang',
    'Paul 500 A2 SA - Satsop Current Mag',
    'Paul 500 A2 SA - Satsop Current Ang',
    'Paul 500 A2 SA - Tono Phase Shifter Current Mag',
    'Paul 500 A2 SA - Tono Phase Shifter Current Ang',
    'Paul 500 A2 SA Frequency',
    'Pearl 500 A1 SA - East Bus Voltage Mag',
    'Pearl 500 A1 SA - East Bus Voltage Ang',
    'Pearl 500 A1 SA - A phase East Bus Voltage Mag',
    'Pearl 500 A1 SA - A phase East Bus Voltage Ang',
    'Pearl 500 A1 SA - B phase East Bus Voltage Mag',
    'Pearl 500 A1 SA - B phase East Bus Voltage Ang',
    'Pearl 500 A1 SA - C phase East Bus Voltage Mag',
    'Pearl 500 A1 SA - C phase East Bus Voltage Ang',
    'Pearl 500 A1 SA - West Bus Voltage Mag',
    'Pearl 500 A1 SA - West Bus Voltage Ang',
    'Pearl 500 A1 SA - A phase West Bus Voltage Mag',
    'Pearl 500 A1 SA - A phase West Bus Voltage Ang',
    'Pearl 500 A1 SA - B phase West Bus Voltage Mag',
    'Pearl 500 A1 SA - B phase West Bus Voltage Ang',
    'Pearl 500 A1 SA - C phase West Bus Voltage Mag',
    'Pearl 500 A1 SA - C phase West Bus Voltage Ang',
    'Pearl 500 A1 SA - Marion #1 Current Mag',
    'Pearl 500 A1 SA - Marion #1 Current Ang',
    'Pearl 500 A1 SA - Keeler #1 Current Mag',
    'Pearl 500 A1 SA - Keeler #1 Current Ang',
    'Pearl 500 A1 SA - Ostrander #1 Current Mag',
    'Pearl 500 A1 SA - Ostrander #1 Current Ang',
    'Pearl 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Pearl 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Pearl 500 A1 SA - Xfmr Bank #2 Current Mag',
    'Pearl 500 A1 SA - Xfmr Bank #2 Current Ang',
    'Pearl 500 A1 SA Frequency',
    'Phalen Gulch data PMU - 230 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - 230 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - A phase 230 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - A phase 230 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - B phase 230 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - B phase 230 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - C phase 230 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - C phase 230 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - 34.5 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - 34.5 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - A phase 34.5 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - A phase 34.5 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - B phase 34.5 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - B phase 34.5 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - C phase 34.5 Main Bus Voltage Mag',
    'Phalen Gulch data PMU - C phase 34.5 Main Bus Voltage Ang',
    'Phalen Gulch data PMU - 230kV main bus Current Mag',
    'Phalen Gulch data PMU - 230kV main bus Current Ang',
    'Phalen Gulch data PMU - 34.5kV main bus Current Mag',
    'Phalen Gulch data PMU - 34.5kV main bus Current Ang',
    'Phalen Gulch data PMU - 34.5kV reactor Current Mag',
    'Phalen Gulch data PMU - 34.5kV reactor Current Ang',
    'Phalen Gulch data PMU Frequency',
    'Rock Creek 230 A1 SA - Xmfr Bank #1 Voltage Mag',
    'Rock Creek 230 A1 SA - Xmfr Bank #1 Voltage Ang',
    'Rock Creek 230 A1 SA - A Phase Xmfr Bank #1 Voltage Mag',
    'Rock Creek 230 A1 SA - A Phase Xmfr Bank #1 Voltage Ang',
    'Rock Creek 230 A1 SA - B Phase Xmfr Bank #1 Voltage Mag',
    'Rock Creek 230 A1 SA - B Phase Xmfr Bank #1 Voltage Ang',
    'Rock Creek 230 A1 SA - C Phase Xmfr Bank #1 Voltage Mag',
    'Rock Creek 230 A1 SA - C Phase Xmfr Bank #1 Voltage Ang',
    'Rock Creek 230 A1 SA - Juniper Canyon #1 Voltage Mag',
    'Rock Creek 230 A1 SA - Juniper Canyon #1 Voltage Ang',
    'Rock Creek 230 A1 SA - A Phase Juniper Canyon #1 Voltage Mag',
    'Rock Creek 230 A1 SA - A Phase Juniper Canyon #1 Voltage Ang',
    'Rock Creek 230 A1 SA - B Phase Juniper Canyon #1 Voltage Mag',
    'Rock Creek 230 A1 SA - B Phase Juniper Canyon #1 Voltage Ang',
    'Rock Creek 230 A1 SA - C Phase Juniper Canyon #1 Voltage Mag',
    'Rock Creek 230 A1 SA - C Phase Juniper Canyon #1 Voltage Ang',
    'Rock Creek 230 A1 SA - Imrie #1 Current Mag',
    'Rock Creek 230 A1 SA - Imrie #1 Current Ang',
    'Rock Creek 230 A1 SA - White Creek #1 Current Mag',
    'Rock Creek 230 A1 SA - White Creek #1 Current Ang',
    'Rock Creek 230 A1 SA - Juniper Canyon #1 Current Mag',
    'Rock Creek 230 A1 SA - Juniper Canyon #1 Current Ang',
    'Rock Creek 230 A1 SA - Energizer #1 Current Mag',
    'Rock Creek 230 A1 SA - Energizer #1 Current Ang',
    'Rock Creek 230 A1 SA - Xfmr Bank #1 Current Mag',
    'Rock Creek 230 A1 SA - Xfmr Bank #1 Current Ang',
    'Rock Creek 230 A1 SA Frequency',
    'Rock Creek 500 A1 SA - West Bus Voltage Mag',
    'Rock Creek 500 A1 SA - West Bus Voltage Ang',
    'Rock Creek 500 A1 SA - A phase West Bus Voltage Mag',
    'Rock Creek 500 A1 SA - A phase West Bus Voltage Ang',
    'Rock Creek 500 A1 SA - B phase West Bus Voltage Mag',
    'Rock Creek 500 A1 SA - B phase West Bus Voltage Ang',
    'Rock Creek 500 A1 SA - C phase West Bus Voltage Mag',
    'Rock Creek 500 A1 SA - C phase West Bus Voltage Ang',
    'Rock Creek 500 A1 SA - Wautoma #1 Voltage Mag',
    'Rock Creek 500 A1 SA - Wautoma #1 Voltage Ang',
    'Rock Creek 500 A1 SA - A Phase Wautoma #1 Voltage Mag',
    'Rock Creek 500 A1 SA - A Phase Wautoma #1 Voltage Ang',
    'Rock Creek 500 A1 SA - B Phase Wautoma #1 Voltage Mag',
    'Rock Creek 500 A1 SA - B Phase Wautoma #1 Voltage Ang',
    'Rock Creek 500 A1 SA - C Phase Wautoma #1 Voltage Mag',
    'Rock Creek 500 A1 SA - C Phase Wautoma #1 Voltage Ang',
    'Rock Creek 500 A1 SA - Wautoma #1 Current Mag',
    'Rock Creek 500 A1 SA - Wautoma #1 Current Ang',
    'Rock Creek 500 A1 SA - John Day #1 Current Mag',
    'Rock Creek 500 A1 SA - John Day #1 Current Ang',
    'Rock Creek 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Rock Creek 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Rock Creek 500 A1 SA Frequency',
    'Schultz 500 A1 SA - East Bus Voltage Mag',
    'Schultz 500 A1 SA - East Bus Voltage Ang',
    'Schultz 500 A1 SA - A phase East Bus Voltage Mag',
    'Schultz 500 A1 SA - A phase East Bus Voltage Ang',
    'Schultz 500 A1 SA - B phase East Bus Voltage Mag',
    'Schultz 500 A1 SA - B phase East Bus Voltage Ang',
    'Schultz 500 A1 SA - C phase East Bus Voltage Mag',
    'Schultz 500 A1 SA - C phase East Bus Voltage Ang',
    'Schultz 500 A1 SA - West Bus Voltage Mag',
    'Schultz 500 A1 SA - West Bus Voltage Ang',
    'Schultz 500 A1 SA - A phase West Bus Voltage Mag',
    'Schultz 500 A1 SA - A phase West Bus Voltage Ang',
    'Schultz 500 A1 SA - B phase West Bus Voltage Mag',
    'Schultz 500 A1 SA - B phase West Bus Voltage Ang',
    'Schultz 500 A1 SA - C phase West Bus Voltage Mag',
    'Schultz 500 A1 SA - C phase West Bus Voltage Ang',
    'Schultz 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Schultz 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Schultz 500 A1 SA - Sickler #1 Current Mag',
    'Schultz 500 A1 SA - Sickler #1 Current Ang',
    'Schultz 500 A1 SA - Grand Coulee #2 Current Mag',
    'Schultz 500 A1 SA - Grand Coulee #2 Current Ang',
    'Schultz 500 A1 SA - Echo Lake #1 Current Mag',
    'Schultz 500 A1 SA - Echo Lake #1 Current Ang',
    'Schultz 500 A1 SA - Grand Coulee #1 Current Mag',
    'Schultz 500 A1 SA - Grand Coulee #1 Current Ang',
    'Schultz 500 A1 SA - Raver #1 Current Mag',
    'Schultz 500 A1 SA - Raver #1 Current Ang',
    'Schultz 500 A1 SA Frequency',
    'Schultz 500 A2 SA - East Bus Voltage Mag',
    'Schultz 500 A2 SA - East Bus Voltage Ang',
    'Schultz 500 A2 SA - A phase East Bus Voltage Mag',
    'Schultz 500 A2 SA - A phase East Bus Voltage Ang',
    'Schultz 500 A2 SA - B phase East Bus Voltage Mag',
    'Schultz 500 A2 SA - B phase East Bus Voltage Ang',
    'Schultz 500 A2 SA - C phase East Bus Voltage Mag',
    'Schultz 500 A2 SA - C phase East Bus Voltage Ang',
    'Schultz 500 A2 SA - West Bus Voltage Mag',
    'Schultz 500 A2 SA - West Bus Voltage Ang',
    'Schultz 500 A2 SA - A phase West Bus Voltage Mag',
    'Schultz 500 A2 SA - A phase West Bus Voltage Ang',
    'Schultz 500 A2 SA - B phase West Bus Voltage Mag',
    'Schultz 500 A2 SA - B phase West Bus Voltage Ang',
    'Schultz 500 A2 SA - C phase West Bus Voltage Mag',
    'Schultz 500 A2 SA - C phase West Bus Voltage Ang',
    'Schultz 500 A2 SA - Wautoma #1 Current Mag',
    'Schultz 500 A2 SA - Wautoma #1 Current Ang',
    'Schultz 500 A2 SA - Raver #3 Current Mag',
    'Schultz 500 A2 SA - Raver #3 Current Ang',
    'Schultz 500 A2 SA - Vantage #1 Current Mag',
    'Schultz 500 A2 SA - Vantage #1 Current Ang',
    'Schultz 500 A2 SA - Raver #4 Current Mag',
    'Schultz 500 A2 SA - Raver #4 Current Ang',
    'Schultz 500 A2 SA Frequency',
    'Slatt 230 A1 SA - East Bus Voltage Mag',
    'Slatt 230 A1 SA - East Bus Voltage Ang',
    'Slatt 230 A1 SA - A phase East Bus Voltage Mag',
    'Slatt 230 A1 SA - A phase East Bus Voltage Ang',
    'Slatt 230 A1 SA - B phase East Bus Voltage Mag',
    'Slatt 230 A1 SA - B phase East Bus Voltage Ang',
    'Slatt 230 A1 SA - C phase East Bus Voltage Mag',
    'Slatt 230 A1 SA - C phase East Bus Voltage Ang',
    'Slatt 230 A1 SA - West Bus Voltage Mag',
    'Slatt 230 A1 SA - West Bus Voltage Ang',
    'Slatt 230 A1 SA - A phase West Bus Voltage Mag',
    'Slatt 230 A1 SA - A phase West Bus Voltage Ang',
    'Slatt 230 A1 SA - B phase West Bus Voltage Mag',
    'Slatt 230 A1 SA - B phase West Bus Voltage Ang',
    'Slatt 230 A1 SA - C phase West Bus Voltage Mag',
    'Slatt 230 A1 SA - C phase West Bus Voltage Ang',
    'Slatt 230 A1 SA - Shepherds Flat #1 Current Mag',
    'Slatt 230 A1 SA - Shepherds Flat #1 Current Ang',
    'Slatt 230 A1 SA - Shepherds Flat #2 Current Mag',
    'Slatt 230 A1 SA - Shepherds Flat #2 Current Ang',
    'Slatt 230 A1 SA - Xfmr Bank #1 Current Mag',
    'Slatt 230 A1 SA - Xfmr Bank #1 Current Ang',
    'Slatt 230 A1 SA - Cap Group #1 Current Mag',
    'Slatt 230 A1 SA - Cap Group #1 Current Ang',
    'Slatt 230 A1 SA - Cap Group #2 Current Mag',
    'Slatt 230 A1 SA - Cap Group #2 Current Ang',
    'Slatt 230 A1 SA Frequency',
    'Slatt 500 A1 SA - East Bus Voltage Mag',
    'Slatt 500 A1 SA - East Bus Voltage Ang',
    'Slatt 500 A1 SA - A phase East Bus Voltage Mag',
    'Slatt 500 A1 SA - A phase East Bus Voltage Ang',
    'Slatt 500 A1 SA - B phase East Bus Voltage Mag',
    'Slatt 500 A1 SA - B phase East Bus Voltage Ang',
    'Slatt 500 A1 SA - C phase East Bus Voltage Mag',
    'Slatt 500 A1 SA - C phase East Bus Voltage Ang',
    'Slatt 500 A1 SA - West Bus Voltage Mag',
    'Slatt 500 A1 SA - West Bus Voltage Ang',
    'Slatt 500 A1 SA - A phase West Bus Voltage Mag',
    'Slatt 500 A1 SA - A phase West Bus Voltage Ang',
    'Slatt 500 A1 SA - B phase West Bus Voltage Mag',
    'Slatt 500 A1 SA - B phase West Bus Voltage Ang',
    'Slatt 500 A1 SA - C phase West Bus Voltage Mag',
    'Slatt 500 A1 SA - C phase West Bus Voltage Ang',
    'Slatt 500 A1 SA - Xfmr Bank #1 Current Mag',
    'Slatt 500 A1 SA - Xfmr Bank #1 Current Ang',
    'Slatt 500 A1 SA - Buckley #1 Current Mag',
    'Slatt 500 A1 SA - Buckley #1 Current Ang',
    'Slatt 500 A1 SA - Boardman #1 Current Mag',
    'Slatt 500 A1 SA - Boardman #1 Current Ang',
    'Slatt 500 A1 SA - Ashe #1 Current Mag',
    'Slatt 500 A1 SA - Ashe #1 Current Ang',
    'Slatt 500 A1 SA - John Day #1 Current Mag',
    'Slatt 500 A1 SA - John Day #1 Current Ang',
    'Slatt 500 A1 SA - Coyote Springs #1 Current Mag',
    'Slatt 500 A1 SA - Coyote Springs #1 Current Ang',
    'Slatt 500 A1 SA Frequency',
    'Summer Lake 500 A1 SA - Summer Lake-Grizzly Voltage Mag',
    'Summer Lake 500 A1 SA - Summer Lake-Grizzly Voltage Ang',
    'Summer Lake 500 A1 SA - A phase Summer Lake-Grizzly Voltage Mag',
    'Summer Lake 500 A1 SA - A phase Summer Lake-Grizzly Voltage Ang',
    'Summer Lake 500 A1 SA - B phase Summer Lake-Grizzly Voltage Mag',
    'Summer Lake 500 A1 SA - B phase Summer Lake-Grizzly Voltage Ang',
    'Summer Lake 500 A1 SA - C phase Summer Lake-Grizzly Voltage Mag',
    'Summer Lake 500 A1 SA - C phase Summer Lake-Grizzly Voltage Ang',
    'Summer Lake 500 A1 SA - Summer Lake-Midpoint Voltage Mag',
    'Summer Lake 500 A1 SA - Summer Lake-Midpoint Voltage Ang',
    'Summer Lake 500 A1 SA - A phase Summer Lake-Midpoint Voltage Mag',
    'Summer Lake 500 A1 SA - A phase Summer Lake-Midpoint Voltage Ang',
    'Summer Lake 500 A1 SA - B phase Summer Lake-Midpoint Voltage Mag',
    'Summer Lake 500 A1 SA - B phase Summer Lake-Midpoint Voltage Ang',
    'Summer Lake 500 A1 SA - C phase Summer Lake-Midpoint Voltage Mag',
    'Summer Lake 500 A1 SA - C phase Summer Lake-Midpoint Voltage Ang',
    'Summer Lake 500 A1 SA - Malin #1 Current Mag',
    'Summer Lake 500 A1 SA - Malin #1 Current Ang',
    'Summer Lake 500 A1 SA - Grizzly #1 Current Mag',
    'Summer Lake 500 A1 SA - Grizzly #1 Current Ang',
    'Summer Lake 500 A1 SA - Midpoint #1 Current Mag',
    'Summer Lake 500 A1 SA - Midpoint #1 Current Ang',
    'Summer Lake 500 A1 SA Frequency',
    'Troutdale 230 A1 SA - West Bus Voltage Mag',
    'Troutdale 230 A1 SA - West Bus Voltage Ang',
    'Troutdale 230 A1 SA - A Phase West Bus Voltage Mag',
    'Troutdale 230 A1 SA - A Phase West Bus Voltage Ang',
    'Troutdale 230 A1 SA - B Phase West Bus Voltage Mag',
    'Troutdale 230 A1 SA - B Phase West Bus Voltage Ang',
    'Troutdale 230 A1 SA - C Phase West Bus Voltage Mag',
    'Troutdale 230 A1 SA - C Phase West Bus Voltage Ang',
    'Troutdale 230 A1 SA - East Bus Voltage Mag',
    'Troutdale 230 A1 SA - East Bus Voltage Ang',
    'Troutdale 230 A1 SA - A Phase East Bus Voltage Mag',
    'Troutdale 230 A1 SA - A Phase East Bus Voltage Ang',
    'Troutdale 230 A1 SA - B Phase East Bus Voltage Mag',
    'Troutdale 230 A1 SA - B Phase East Bus Voltage Ang',
    'Troutdale 230 A1 SA - C Phase East Bus Voltage Mag',
    'Troutdale 230 A1 SA - C Phase East Bus Voltage Ang',
    'Troutdale 230 A1 SA - Big Eddy Current Mag',
    'Troutdale 230 A1 SA - Big Eddy Current Ang',
    'Troutdale 230 A1 SA - N. Bonneville #1 Current Mag',
    'Troutdale 230 A1 SA - N. Bonneville #1 Current Ang',
    'Troutdale 230 A1 SA - N. Bonneville #2 Current Mag',
    'Troutdale 230 A1 SA - N. Bonneville #2 Current Ang',
    'Troutdale 230 A1 SA - Bus Tie #1 Current Mag',
    'Troutdale 230 A1 SA - Bus Tie #1 Current Ang',
    'Troutdale 230 A1 SA - Bus Tie #2 Current Mag',
    'Troutdale 230 A1 SA - Bus Tie #2 Current Ang',
    'Troutdale 230 A1 SA - Ostrander/Bank #8 Current Mag',
    'Troutdale 230 A1 SA - Ostrander/Bank #8 Current Ang',
    'Troutdale 230 A1 SA Frequency',
    'Wautoma 500 A1 SA - East Bus Voltage Mag',
    'Wautoma 500 A1 SA - East Bus Voltage Ang',
    'Wautoma 500 A1 SA - A phase East Bus Voltage Mag',
    'Wautoma 500 A1 SA - A phase East Bus Voltage Ang',
    'Wautoma 500 A1 SA - B phase East Bus Voltage Mag',
    'Wautoma 500 A1 SA - B phase East Bus Voltage Ang',
    'Wautoma 500 A1 SA - C phase East Bus Voltage Mag',
    'Wautoma 500 A1 SA - C phase East Bus Voltage Ang',
    'Wautoma 500 A1 SA - West Bus Voltage Mag',
    'Wautoma 500 A1 SA - West Bus Voltage Ang',
    'Wautoma 500 A1 SA - A phase West Bus Voltage Mag',
    'Wautoma 500 A1 SA - A phase West Bus Voltage Ang',
    'Wautoma 500 A1 SA - B phase West Bus Voltage Mag',
    'Wautoma 500 A1 SA - B phase West Bus Voltage Ang',
    'Wautoma 500 A1 SA - C phase West Bus Voltage Mag',
    'Wautoma 500 A1 SA - C phase West Bus Voltage Ang',
    'Wautoma 500 A1 SA - Schultz #1 Current Mag',
    'Wautoma 500 A1 SA - Schultz #1 Current Ang',
    'Wautoma 500 A1 SA - Knight #1 Current Mag',
    'Wautoma 500 A1 SA - Knight #1 Current Ang',
    'Wautoma 500 A1 SA - Hanford #1 Current Mag',
    'Wautoma 500 A1 SA - Hanford #1 Current Ang',
    'Wautoma 500 A1 SA - Rock Creek #1 Current Mag',
    'Wautoma 500 A1 SA - Rock Creek #1 Current Ang',
    'Wautoma 500 A1 SA - Hanford #2 Current Mag',
    'Wautoma 500 A1 SA - Hanford #2 Current Ang',
    'Wautoma 500 A1 SA Frequency']

 
if __name__ == "__main__":
    import doctest
    doctest.testmod()

    
